lag_code_map = {
    'en': 'English',
    'ar':'Arabic',
    'bn': 'Bengali',
    'cs': 'Czech',
    'da': 'Danish',
    'de': 'German',
    'el': 'Greek',
    'es': 'Spanish',
    'fa': 'Persian',
    'fi': 'Finnish',
    'fil': 'Filipino',
    'fr': 'French',
    'he': 'Hebrew',
    'hi': 'Hindi',
    'hu': 'Hungarian',
    'id': 'Indonesian',
    'it': 'Italian',
    'ja': 'Japanese',
    'ko': 'Korean',
    'msa': 'Malay',
    'nl': 'Dutch',
    'no': 'Norwegian',
    'pl': 'Polish',
    'ro': 'Romanian',
    'ru': 'Russian',
    'sv': 'Swedish',
    'th': 'Thai',
    'tr': 'Turkish',
    'uk': 'Ukrainian',
    'ur': 'Urdu',
    'vi': 'Swedish',
    'zh-cn': 'Chinese',
    'zh-tw': 'Chinese',
    'zh':'Chinese',
    'et': 'Estonian',
    'in': 'Hindi',
    'tl':'Tagalog',
    'pt': 'Portuguese',
    'ht':'Haitian Creole',
    'iw':'Hebrew',
    'eu':'Basque',
    'cy':'Welsh',
    'lv':'Latvian',
    'lt':'Lithuanian',
    'sl':'Slovenian'
}