# Common vars
availability_zone: melbourne-qh2-uom
instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
instance_key_name: zheng
instance_flavor: uom.mse.2c9g

# Volume
volumes:
  - vol_name: backend-volume
    vol_size: 60
    device: /dev/vdb
    mountpoint: /data

# Security group
security_groups:
  - name: ssh-sg
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http-sg
    description: "Security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: backend-instance
    volumes: ['backend-volume']
