---
- name: pull docker image from docker hub
  become:
    yes
  shell: docker pull zheng0518/comp90024-frontend

- name: start the container
  become:
    yes
  shell: docker run -d -p 80:3000 --name='comp90024-frontend' -e BACKEND_IP=http://{{ groups['backend-instance'][0] }}:80 zheng0518/comp90024-frontend