---
- name: pull docker image from docker hub
  become:
    yes
  shell: docker pull zheng0518/comp90024-backend

- name: start the container
  become:
    yes
  shell: docker run -d -p 80:5000 --name='comp90024-backend' zheng0518/comp90024-backend