---
- name: Uninstall old versions of docker
  become: yes
  apt:
    name: ['docker', 'docker-engine', 'docker.io']
    state: absent

- name: Add Docker apt repository key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker apt repository and update apt cache
  become: yes
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    mode: '644'
    update_cache: yes
    state: present

- name: Install docker
  become: yes
  apt:
    name: ['docker-ce']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Install docker-compose
  become: yes
  pip:
    name: ['docker-compose']
    state: latest

- name: add user to docker group 
  become: yes
  shell: gpasswd -a {{ansible_user}} docker