- hosts: localhost
  vars_files:
    - host_vars/common_vars.yaml
  gather_facts: true

  roles:
    - role: volume-creation
    - role: security-group-creation
    - role: instance-creation

- hosts: COMP90024
  vars_files:
    - host_vars/common_vars.yaml
  gather_facts: true

  roles:
    - role: instance-configuration
    - role: docker-setup